function [BW,maskedImage] = segmentImage(X)
%segmentImage Segment image using auto-generated code from Image Segmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the Image Segmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 18-Oct-2023
%----------------------------------------------------


% Normalize input data to range in [0,1].
Xmin = min(X(:));
Xmax = max(X(:));
if isequal(Xmax,Xmin)
    X = 0*X;
else
    X = (X - Xmin) ./ (Xmax - Xmin);
end

% Graph cut
foregroundInd = [135205 135206 135213 135218 135225 135246 135250 135256 135260 135281 135282 135289 135304 135310 135313 135320 135324 135333 135339 135343 135374 135379 135388 135399 135407 135417 135422 135428 135435 135447 135458 135462 135469 135500 135505 135509 135516 135518 140242 ];
backgroundInd = [63701 63703 63709 74257 74259 74261 74263 77614 80972 82211 82215 90625 92732 99452 111217 119208 125936 128023 133066 134341 136428 143152 144427 153242 154513 162918 168373 171735 173004 186866 202002 206624 208728 209986 215454 223859 225115 227230 228477 235197 237326 238557 241915 241917 245742 245744 245751 245764 245766 245768 246951 253675 ];
L = superpixels(X,1647);
BW = lazysnapping(X,L,foregroundInd,backgroundInd);

% Clear borders
BW = imclearborder(BW);

% Active contour
iterations = 50;
BW = activecontour(X, BW, iterations, 'Chan-Vese');

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end

